name: Expo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-

    - name: Install dependencies
      run: npm install

    - name: Run TypeScript type check
      run: npm run ts:check

    - name: Install ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick

    - name: Create placeholder images
      run: |
        mkdir -p assets/images
        convert -size 1024x1024 xc:transparent assets/images/icon.png
        convert -size 1024x1024 xc:transparent assets/images/splash.png
        convert -size 1024x1024 xc:transparent assets/images/adaptive-icon.png

    - name: Install Expo CLI
      run: npm install -g expo-cli

    - name: Cache Expo modules
      uses: actions/cache@v3
      with:
        path: ~/.expo
        key: ${{ runner.OS }}-expo-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.OS }}-expo-

    - name: Check Expo project
      run: npx expo-doctor

    - name: Build Expo web
      run: npx expo export:web

    - name: Upload web build artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: web-build
